require_relative 'opengraph'
MyApp.helpers OGParser
require_relative 'oauth'
MyApp.helpers OAuth
require_relative 'recipes'
MyApp.helpers Recipes
require_relative 'invites'
MyApp.helpers Invites
require_relative 'openai'
MyApp.helpers OpenAI
require_relative 'groups'
MyApp.helpers Groups
require_relative 'recommendation'
MyApp.helpers Recommendation
require_relative 'search'
MyApp.helpers Search